---
info:
  django_settings: mw_webscrape.settings
  profile_name: your_aws_profile_in_credentials_file # Using this profile for both zappa and writing to S3, see README for more info
  project_name": your_project_name 
  aws_region: 'e.g., us-east-2'
  runtime: python3.6
  keep_warm: true
  # domain: "yourapp.yourdomain.com" # not using
  s3_bucket: "your bucket"
  slim_handler: true
  timeout_seconds: 300
  events:
    - function: "mw.views.baker_report"
      expression: "cron(55 0/2 ? * MON-TUE *)"
    - function: "mw.views.baker_report_wednesday"
      expression: "cron(55 0,2,4, ? * WED *)"
  aws_environment_variables:
    DEBUG: "on"
    VARS_ENCRYPTED: "on"
    # settings for site to scrape:
    USER: "some user_encrypted_with_encrypted_helper"
    PW: "some passwd_encrypted_with_encrypted_helper"
    URL: "some url"
    DASHBOARD: "some url"
    ORDERS: "some url"
    BUCKET_NAME: your_bucket_name
    REGION_NAME: your_bucket_region
    RESULTFILE_NAME: file_name

# Keep this file in a secure place

# vim: ai et ts=2 sts=2 sw=2 nu ru
